services:
  db:
    container_name: postgresuv

  tomcat:
    image: tomcat:9.0.87-jdk11
    container_name: tomcat-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ejemplo
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /c/Users/Danielaa/Desktop/DESARROLLO/PRACTICAS\ TOMCAT/DAAP01Practica05/target:/usr/local/tomcat/webapps
    command: /bin/bash -c "cp /usr/local/tomcat/webapps/DAPP01Practica05-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war && catalina.sh run"
    restart: always

  frontend:
    image: front
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - tomcat