services:
  postgresuv:
    image: postgres:12.18
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ejemplo
    container_name: postgresuv
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  tomcat-api:
    image: tomcat-api
    ports:
      - 8000:8080
    container_name: tomcat-api
    depends_on:
      - postgresuv
    restart: always
    build: .

  frontend:
    image: front
    ports:
      - 4200:80
    restart: always
    depends_on:
      - tomcat-api